import type { Metadata } from "next";
import Layout from "@/components/Layout";
import "./globals.css";
import { getSession } from "@/lib/session";

export const metadata: Metadata = {
  title: "SkillRoute",
  description: "Generated by create next app",
  keywords: ["Next.js", "React", "TypeScript"],
  authors: [{ name: "Razeen Shaikh" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await getSession();

  return (
    <html lang="en" className="h-full" suppressHydrationWarning><body className="h-screen w-screen overflow-hidden">
        <Layout session={session}>{children}</Layout>
      </body></html>
  );
}
