import Layout from "@/components/Layout";
import "./globals.css";
import { authOptions } from "@/lib/authOptions";
import { getServerSession } from "next-auth";

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await getServerSession(authOptions)

  return (
    <html lang="en" className="h-full">
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="Next.js, React, TypeScript" />
        <meta name="author" content="Razeen Shaikh" />
        <title>SkillRoute</title>
      </head>
      <body className="h-screen w-screen overflow-hidden">
        <Layout session={session}>{children}</Layout>
      </body>
    </html>
  );
}
