name: Cypress Tests
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Start Next.js App
        run: npm run dev &

      - name: Run Cypress Tests
        run: npx cypress run
